version: '3.9'

services:
  keycloak:
    image: keycloak/keycloak:24.0.2
    container_name: keycloak
    user: root
    volumes:
      - ./keycloak_data/:/opt/keycloak/data/
      - "./keycloak_data/server.crt.pem:/etc/x509/https/tls.crt"   # Map certificate to container
      - "./keycloak_data/server.key.pem:/etc/x509/https/tls.key"   # Map private key to container
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/tls.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key
    command:
      - start-dev
    ports:
      - 8082:8080
      - 8443:8443
  api_gatway:
    image: devopsfaith/krakend:2.6.0
    container_name: api_gatway_ct
    volumes:
      - ./krakend:/etc/krakend/
    depends_on:
      - inventory_service
      - order_record_service
      - keycloak
    ports:
      - "8080:8081"
  inventory_service:
    build:
      context: ./../../lab6/inventoryservice
    container_name: inventory_service_ct
    ports:
      - "5000:5000"
  order_record_service:
    build:
      context: ./../../lab6/orderrecordservice
    container_name: order_record_service_ct
    ports:
      - "5001:5000"