version: '3.9'

volumes:
  postgres_data:
    driver: local

services:  
  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    user: root
    volumes:
      - ./keycloak_data/:/opt/jboss/keycloak/standalone/data/
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8082:8080
      - 8443:8443
  api_gatway:
    image: devopsfaith/krakend:2.6.0
    container_name: api_gatway_ct
    volumes:
      - ./krakend:/etc/krakend/
    depends_on:
      - inventory_service
      - order_record_service
      - keycloak
    ports:
      - "8080:8081"
  inventory_service:
    build:
      context: ./../../lab5/inventoryservice
    container_name: inventory_service_ct
    ports:
      - "5000:5000"
  order_record_service:
    build:
      context: ./../../lab5/orderrecordservice
    container_name: order_record_service_ct
    ports:
      - "5001:5000"