version: '3.9'
services:  
  api_gatway:
    image: devopsfaith/krakend:2.6.0
    container_name: api_gatway_ct
    volumes:
      - ./krakend:/etc/krakend/
    depends_on:
      - inventory_service
      - order_record_service
    ports:
      - "8080:8081"
  inventory_service:
    build:
      context: ./../../lab6/inventoryservice
    container_name: inventory_service_ct
    ports:
      - "5000:5000"
  order_record_service:
    build:
      context: ./../../lab6/orderrecordservice
    container_name: order_record_service_ct
    ports:
      - "5001:5000"