apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prediction-api
  name: prediction-api
  namespace: myapps
spec:
  replicas: 2 # Creating two replicas of the POD
  selector:
    matchLabels:
      app: prediction-api
  template:
    metadata:
      labels:
        app: prediction-api
    spec:
      containers:
      - image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/prediction-api:0.0.1 # Docker image name, that we pushed to GCR - use your project id, location, and repository
        name: prediction-api
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: PROJECT_ID
          value: ada2024  # use your project id
        - name: MODEL_REPO
          value: ada2024_models # use your GCP bucket id
        - name: MODEL_NAME
          value: model.h5
