version: '3.9'
services:  
  inventory_service:
    build:
      context: ./../inventoryservice
    container_name: inventory_service_ct
    ports:
      - "5000:5000"
  order_record_service:
    build:
      context: ./../orderrecordservice
    container_name: order_record_service_ct
    ports:
      - "5001:5000"
  diabetes_predictor_service:
    build:
      context: ./modelservice
    container_name: diabetes_predictor_service_ct
    ports:
      - "5002:5000"
  supplier_service:
    build:
      context: ./supplierservice
    container_name: supplier_service_ct
    ports:
      - "5003:5000"